# Generated by Django 4.2.7 on 2023-11-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_images/'),
        ),
    ]
